# Helper Methods for energy conversion
# Conversion Data: https://apps.cer-rec.gc.ca/Conversion/conversion-tables.aspx?GoCTemplateCulture=en-CA

# There are 1,000,000 GJ in one PJ
GJ_TO_PJ = 1000000

# Onw MWh is 0.000036 PJ
MWH_TO_PJ = 0.0000036

# Butane, in Cubic Metres
def butane_to_pj(butane):
  return butane * 28.62 / GJ_TO_PJ

# Coal, in tons
# Coal has four different "types" each resulting in different energy densities.
#   Anthracite: 27.70 GJ
#   Bituminous: 27.60 GJ
#   Lignite: 14.40 GJ
#   Subbituminous: 18.80 GJ
def coal_to_pj(coal):
  return coal * 27.60 / GJ_TO_PJ

# Light Crude Oil, in m³
#   Light	1.0 Cubic metres (m³)	38.51 Gigajoules (GJ)
def light_crude_oil_to_pj(crude_oil):
  return crude_oil * 38.41 / GJ_TO_PJ

# Heavy Crude Oil, in m³
#   Heavy	1.0 Cubic metres (m³)	40.90 Gigajoules (GJ)
def heavy_crude_oil_to_pj(crude_oil):
  return crude_oil * 40.90 / GJ_TO_PJ

# C5+, in m³
#   Pentanes plus	1.0 Cubic metres (m³)	35.17 Gigajoules (GJ)
def pentanes_plus_crude_oil_to_pj(crude_oil):
  return crude_oil * 35.17 / GJ_TO_PJ

# Synthetic Crude Oil, in m³
#   Synthetic crude oil	1.0 Cubic metres (m³)	39.40 Gigajoules (GJ)
def synthetic_crude_oil_to_pj(crude_oil):
  return crude_oil * 39.40 / GJ_TO_PJ

# Bitument Crude Oil
#   Bitumen	1.0 Cubic metres (m³)	42.80 Gigajoules (GJ)
def bitumen_crude_oil_to_pj(crude_oil):
  return crude_oil * 42.80 / GJ_TO_PJ

# Ethane, in Cubic Metres
def ethane_to_pj(ethane):
  return ethane * 18.36 / GJ_TO_PJ

# Natural Gas, in Cubic Metres
def natural_gas_to_pj(natural_gas):
  return natural_gas * 0.0373 / GJ_TO_PJ

def pentanes_to_pj(pentanes):
  return pentanes * 35.17 / GJ_TO_PJ

def propane_to_pj(propane):
  return propane * 25.53 / GJ_TO_PJ

# Using https://www.cesarnet.ca/visualization/sankey-diagrams-canadas-energy-systems 's conversion,
# > The primary heat energy generated by uranium depends on the reactor technology being used, and is much higher in reactors that use enriched uranium than in the CANDU natural uranium reactors used in Canada. The typical heat rate for uranium in a CANDU is 7700 MW-days(thermal)/tonne U, which converts to 0.665 PJ/tonne U, and this is the the conversion factor used in this Sankey diagram for estimating the primary energy content of uranium.
def uranium_to_pj(uranium):
  return uranium * 0.665

def gwh_to_pj(gwh):
  # 1 GWh = 3600 GigaJoules
  return gwh * 3600 / GJ_TO_PJ

def extract_value(dataframe, variable, key="Value"):
  if isinstance(variable, list):
    return dataframe[dataframe["Variable"].isin(variable)][key].sum()
  return dataframe[dataframe["Variable"] == variable].iloc[0][key]